### ISSUE TITLE
App freezes during the wallet sync

### ISSUE THREAD

**Issue by rabinvg** [bitcoindevkit/BDKSwiftExampleWallet#127]
When the wallet is syncing, the app freezes until the sync process is completed. Is the sync process being done in main thread?

1. Open app click other buttons.

https://github.com/bitcoindevkit/BDKSwiftExampleWallet/assets/131969426/bc0a1fa9-c374-4ddc-9f3c-c83175094309

**Comment by reez** [comment]
Thanks for opening up this issue!

Using [async await](https://github.com/apple/swift-evolution/blob/main/proposals/0296-async-await.md), the relevant 3 places sync flows thru: 
- [WalletView](https://github.com/bitcoindevkit/BDKSwiftExampleWallet/blob/8862b6768b45ca0e9b212666767485686742b93f/BDKSwiftExampleWallet/View/WalletView.swift#L105) 
- [WalletViewModel](https://github.com/bitcoindevkit/BDKSwiftExampleWallet/blob/8862b6768b45ca0e9b212666767485686742b93f/BDKSwiftExampleWallet/View%20Model/WalletViewModel.swift#L84)
- [BDKService](https://github.com/bitcoindevkit/BDKSwiftExampleWallet/blob/8862b6768b45ca0e9b212666767485686742b93f/BDKSwiftExampleWallet/Service/BDK%20Service/BDKService.swift#L185)

`bdk-swift` v0.31 is currently being used in `BDKSwiftExampleWallet`, under the hood the function generated by [bdk-ffi](https://github.com/bitcoindevkit/bdk-ffi/blob/8d1ecd1d8c6b44b41e350f965a34bd27aa653075/bdk-ffi/src/wallet.rs#L79) for [bdk-swift](https://github.com/bitcoindevkit/bdk-swift/blob/20ca547a69487a41665ad7d92b0f1aa46b84d9d0/Sources/BitcoinDevKit/BitcoinDevKit.swift#L2226) is blocking, but [bdk 1.0](https://bitcoindevkit.org/blog/road-to-bdk-1/) has been started on and is currently in [alpha](https://github.com/bitcoindevkit/bdk/releases/tag/v1.0.0-alpha.6) with [beta](https://github.com/orgs/bitcoindevkit/projects/14) right around the corner. I mention this because `bdk` will change the paradigm for syncing, which will change the way we handle syncing in `BDKSwiftExampleWallet`. If you have suggestions/feedback/PullRequests they are always welcome+valuable!

**Comment by rabinvg** [comment]
Could you please add snippets on how would i get the current balance, list transactions send etc in the 1.0.0. It seems that is is entirely different from the 0.31.0 version.

**Comment by rabinvg** [comment]
Thank you @reez. We are implementing bitcoin support in our crypto wallet. BDK seems to be the best choice. I have been timed out in the channel. Did i violate some rule in the discord?

**Comment by rabinvg** [comment]
@reez I didnt find wallet.transactions() method in bdk-swift 1.0.0-alpha.2a. How do fetch transactions in this version.

**Comment by reez** [comment]
> @reez I didnt find wallet.transactions() method in bdk-swift 1.0.0-alpha.2a. How do fetch transactions in this version.

its in the bdk 1.0.0-alpha.2 but it didn't make the bdk-swift 1.0.0-alpha.2a because it wasn't [merged yet in bdk-ffi](https://github.com/bitcoindevkit/bdk-ffi/commit/a1a45996fc0f5e4a5b00db984c8c886546ce550e). It will be in the next bdk-swift release though since it's been merged.

For bdk-swift 1.0.0-alpha.2a you can take a look at the [BitcoinDevKit.swift](https://github.com/bitcoindevkit/bdk-swift/blob/1.0.0-alpha.2a/Sources/BitcoinDevKit/BitcoinDevKit.swift) file to check out all the code available, but some features may not be available yet, but overtime they are being added.

There is also an option to build the swift bindings yourself from bdk-ffi using this [script](https://github.com/bitcoindevkit/bdk-ffi/blob/master/bdk-swift/build-local-swift.sh), that way you have all the latest and greatest that has been merged related to the swift bindings.

Additionally, if its at all helpful to you I'm happy to take some time with you to go over any large or small questions about pre-1.0 and 1.0 and the process and timeline we are on, as well as any nuances in the code, and any specific topics related to integrating into your code base... Just send me a DM on Discord and we can figure a good time for that if you'd like!

**Comment by reez** [comment]
Closing for now because I have a Draft PR on migrating to 1.0: https://github.com/bitcoindevkit/BDKSwiftExampleWallet/pull/132

Can re-open if needed ever or open a new issue about one specific item of the few we chatted on here-
